# Generated by Django 4.2.29 on 2026-04-06 23:35

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_type', models.CharField(choices=[('upload', 'Upload Video (Uploadcare)'), ('youtube', 'YouTube Link')], default='youtube', max_length=20)),
                ('video_file', pyuploadcare.dj.models.FileField(blank=True, help_text='Upload video file (MP4 recommended)')),
                ('youtube_url', models.URLField(blank=True, help_text='Paste full YouTube URL e.g. https://www.youtube.com/watch?v=...')),
                ('thumbnail', pyuploadcare.dj.models.ImageField(blank=True, help_text='Video thumbnail image')),
                ('product_tag', models.CharField(blank=True, help_text='Related product name (optional)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in top slider')),
                ('order', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video Advertisement',
                'verbose_name_plural': 'Video Advertisements',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
