# Generated by Django 4.2.29 on 2026-04-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoad',
            name='thumbnail',
            field=models.CharField(blank=True, help_text='Uploadcare UUID ya thumbnail image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videoad',
            name='video_file',
            field=models.CharField(blank=True, help_text='Uploadcare UUID ya video (MP4)', max_length=255, null=True),
        ),
    ]
