# Generated by Django 4.2.29 on 2026-04-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videoad_thumbnail_alter_videoad_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoad',
            name='product_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videoad',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste full YouTube URL'),
        ),
    ]
