# Generated by Django 4.2.29 on 2026-04-06 23:35

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('bg_color', models.CharField(default='#1a5c2e', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', max_length=20)),
                ('link', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Announcement Banner',
                'verbose_name_plural': 'Announcement Banners',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Mayila Herbal Clinic', max_length=200)),
                ('tagline', models.CharField(default='Tiba za Asili • Natural Healing', max_length=300)),
                ('logo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('favicon', pyuploadcare.dj.models.ImageField(blank=True)),
                ('primary_color', models.CharField(default='#1a5c2e', help_text='Main green color', max_length=20)),
                ('secondary_color', models.CharField(default='#c9a84c', help_text='Gold accent color', max_length=20)),
                ('dark_color', models.CharField(default='#0d1f0f', max_length=20)),
                ('light_color', models.CharField(default='#f5f0e8', max_length=20)),
                ('text_color', models.CharField(default='#1a1a1a', max_length=20)),
                ('hero_title', models.CharField(default="Nature's Power, Your Health", max_length=300)),
                ('hero_subtitle', models.TextField(default='100% Natural Herbal Products — Certified & Trusted\nBidhaa za Asili Zilizo Salama na Zenye Ufanisi')),
                ('hero_bg_image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('hero_cta_text', models.CharField(default='Explore Products', max_length=100)),
                ('hero_cta2_text', models.CharField(default='Contact Us', max_length=100)),
                ('about_title', models.CharField(default='About Mayila Herbal Clinic', max_length=200)),
                ('about_text', models.TextField(default='Mayila Herbal Clinic ni kituo cha tiba za asili kilichopo Mbalizi, Mbeya, Tanzania.\n\nKituo kimesajiliwa na Wizara ya Afya chini ya namba ya usajili MBY/136/TP/00112/2023, na kinajihusisha na utoaji wa tiba za asili pamoja na ushauri wa kiafya kwa watu wenye changamoto mbalimbali za kiafya.\n\nTaasisi hii ilianzishwa kwa lengo la kusaidia jamii kupata tiba mbadala iliyo salama, nafuu, na yenye matokeo chanya bila madhara makubwa kiafya.')),
                ('about_image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('registration_no', models.CharField(default='MBY/136/TP/00112/2023', max_length=100)),
                ('vision_text', models.TextField(default='Kuunda jamii yenye afya bora kupitia tiba za asili salama, nafuu na zenye ufanisi.')),
                ('mission_text', models.TextField(default='• Kutoa tiba za asili salama na zenye ufanisi kwa wagonjwa.\n• Kutoa ushauri wa kiafya wa karibu na wa kibinafsi.\n• Kujenga uaminifu na matokeo chanya kwa wagonjwa.\n• Kuendeleza elimu ya tiba za asili kwa jamii.')),
                ('stat1_number', models.CharField(default='7+', max_length=20)),
                ('stat1_label', models.CharField(default='Herbal Products', max_length=100)),
                ('stat2_number', models.CharField(default='1000+', max_length=20)),
                ('stat2_label', models.CharField(default='Happy Clients', max_length=100)),
                ('stat3_number', models.CharField(default='100%', max_length=20)),
                ('stat3_label', models.CharField(default='Natural Ingredients', max_length=100)),
                ('stat4_number', models.CharField(default='2023', max_length=20)),
                ('stat4_label', models.CharField(default='Est. Year', max_length=100)),
                ('phone1', models.CharField(default='+255676718040', max_length=30)),
                ('phone2', models.CharField(blank=True, default='+255762518040', max_length=30)),
                ('email', models.EmailField(blank=True, default='mayilaherbalclinic@gmail.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='+255676718040', help_text='Include country code e.g. +255676718040', max_length=30)),
                ('whatsapp_message', models.CharField(default='Hello! I am interested in your herbal products.', max_length=300)),
                ('location', models.CharField(default='Mbalizi, Mbeya, Tanzania', max_length=300)),
                ('google_maps_embed', models.TextField(blank=True, help_text='Paste full Google Maps embed iframe code')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('footer_text', models.TextField(default='© Mayila Herbal Clinic. All rights reserved. | Mbalizi, Mbeya, Tanzania')),
                ('footer_tagline', models.CharField(default='Afya ni Hazina — Health is Wealth', max_length=300)),
                ('meta_description', models.TextField(default='Mayila Herbal Clinic — Natural herbal products from Mbeya, Tanzania. 100% natural, safe and effective herbal medicine.')),
                ('meta_keywords', models.TextField(default='herbal clinic, tiba za asili, Mbeya, Tanzania, natural medicine, mdindadinda, mvyei, msuli pawa, dumetex, master clean')),
                ('products_section_title', models.CharField(default='Our Products', max_length=200)),
                ('products_section_subtitle', models.CharField(default='Bidhaa Zetu za Asili — 100% Natural & Certified', max_length=300)),
                ('videos_section_title', models.CharField(default='Product Advertisements', max_length=200)),
                ('videos_section_subtitle', models.CharField(default='Watch our latest product videos — Tazama matangazo yetu', max_length=300)),
                ('testimonials_title', models.CharField(default='What Our Clients Say', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('photo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('product', models.CharField(blank=True, help_text='Which product helped them?', max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
