# Generated by Django 4.2.29 on 2026-04-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_bg_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.CharField(blank=True, help_text='Uploadcare UUID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
