# Generated by Django 4.2.29 on 2026-04-06 23:35

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('main_image', pyuploadcare.dj.models.ImageField(help_text='Main product image')),
                ('image2', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image3', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image4', pyuploadcare.dj.models.ImageField(blank=True)),
                ('short_desc', models.CharField(help_text='Short tagline shown on cards', max_length=300)),
                ('description', models.TextField(help_text='Full product description')),
                ('benefits', models.TextField(blank=True, help_text='One benefit per line')),
                ('ingredients', models.TextField(blank=True)),
                ('usage', models.TextField(blank=True, help_text='How to use / Jinsi ya kutumia')),
                ('volume', models.CharField(blank=True, help_text='e.g. 500ml, 400ml', max_length=50)),
                ('targets', models.CharField(blank=True, help_text="e.g. Men's health, Women's health, Diabetes", max_length=300)),
                ('badge', models.CharField(blank=True, choices=[('bestseller', '🔥 Best Seller'), ('new', '✨ New'), ('natural', '🌿 100% Natural'), ('featured', '⭐ Featured'), ('', 'No Badge')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in hero slider')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('whatsapp_message', models.CharField(blank=True, help_text='Custom WhatsApp message for this product. Leave blank for default.', max_length=300)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order', 'name'],
            },
        ),
    ]
