# Generated by Django 4.2.29 on 2026-04-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image2_alter_product_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.CharField(blank=True, default=1, help_text='Uploadcare CDN URL - main image'),
            preserve_default=False,
        ),
    ]
