# Generated by Django 4.2.29 on 2026-05-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Bei ya bidhaa kwa TZS (optional — inaonekana kwenye Google rich results)', max_digits=10, null=True),
        ),
    ]
